/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef block_registration_service_TYPES_H
#define block_registration_service_TYPES_H

#include <iosfwd>

#include <thrift/Thrift.h>
#include <thrift/TApplicationException.h>
#include <thrift/TBase.h>
#include <thrift/protocol/TProtocol.h>
#include <thrift/transport/TTransport.h>

#include <functional>
#include <memory>


namespace hive { namespace metadata {

class block_registration_service_exception;

typedef struct _block_registration_service_exception__isset {
  _block_registration_service_exception__isset() : msg(false) {}
  bool msg :1;
} _block_registration_service_exception__isset;

class block_registration_service_exception : public ::apache::thrift::TException {
 public:

  block_registration_service_exception(const block_registration_service_exception&);
  block_registration_service_exception& operator=(const block_registration_service_exception&);
  block_registration_service_exception() noexcept
                                       : msg() {
  }

  virtual ~block_registration_service_exception() noexcept;
  std::string msg;

  _block_registration_service_exception__isset __isset;

  void __set_msg(const std::string& val);

  bool operator == (const block_registration_service_exception & rhs) const
  {
    if (!(msg == rhs.msg))
      return false;
    return true;
  }
  bool operator != (const block_registration_service_exception &rhs) const {
    return !(*this == rhs);
  }

  bool operator < (const block_registration_service_exception & ) const;

  template <class Protocol_>
  uint32_t read(Protocol_* iprot);
  template <class Protocol_>
  uint32_t write(Protocol_* oprot) const;

  virtual void printTo(std::ostream& out) const;
  mutable std::string thriftTExceptionMessageHolder_;
  const char* what() const noexcept override;
};

void swap(block_registration_service_exception &a, block_registration_service_exception &b);

std::ostream& operator<<(std::ostream& out, const block_registration_service_exception& obj);

}} // namespace

#include "block_registration_service_types.tcc"

#endif
