/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "block_registration_service.h"
#include "block_registration_service.tcc"

namespace hive { namespace metadata {


block_registration_service_add_blocks_args::~block_registration_service_add_blocks_args() noexcept {
}


block_registration_service_add_blocks_pargs::~block_registration_service_add_blocks_pargs() noexcept {
}


block_registration_service_add_blocks_result::~block_registration_service_add_blocks_result() noexcept {
}


block_registration_service_add_blocks_presult::~block_registration_service_add_blocks_presult() noexcept {
}


block_registration_service_remove_blocks_args::~block_registration_service_remove_blocks_args() noexcept {
}


block_registration_service_remove_blocks_pargs::~block_registration_service_remove_blocks_pargs() noexcept {
}


block_registration_service_remove_blocks_result::~block_registration_service_remove_blocks_result() noexcept {
}


block_registration_service_remove_blocks_presult::~block_registration_service_remove_blocks_presult() noexcept {
}

}} // namespace

