/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "inference_service.h"
#include "inference_service.tcc"

namespace hive { namespace predictor {


inference_service_inference_args::~inference_service_inference_args() noexcept {
}


inference_service_inference_pargs::~inference_service_inference_pargs() noexcept {
}


inference_service_inference_result::~inference_service_inference_result() noexcept {
}


inference_service_inference_presult::~inference_service_inference_presult() noexcept {
}

}} // namespace

