/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "inode_management_service.h"
#include "inode_management_service.tcc"

namespace hive { namespace metadata {


inode_management_service_put_lf_args::~inode_management_service_put_lf_args() noexcept {
}


inode_management_service_put_lf_pargs::~inode_management_service_put_lf_pargs() noexcept {
}


inode_management_service_put_lf_result::~inode_management_service_put_lf_result() noexcept {
}


inode_management_service_put_lf_presult::~inode_management_service_put_lf_presult() noexcept {
}


inode_management_service_put_args::~inode_management_service_put_args() noexcept {
}


inode_management_service_put_pargs::~inode_management_service_put_pargs() noexcept {
}


inode_management_service_put_result::~inode_management_service_put_result() noexcept {
}


inode_management_service_put_presult::~inode_management_service_put_presult() noexcept {
}


inode_management_service_get_args::~inode_management_service_get_args() noexcept {
}


inode_management_service_get_pargs::~inode_management_service_get_pargs() noexcept {
}


inode_management_service_get_result::~inode_management_service_get_result() noexcept {
}


inode_management_service_get_presult::~inode_management_service_get_presult() noexcept {
}


inode_management_service_remove_args::~inode_management_service_remove_args() noexcept {
}


inode_management_service_remove_pargs::~inode_management_service_remove_pargs() noexcept {
}


inode_management_service_remove_result::~inode_management_service_remove_result() noexcept {
}


inode_management_service_remove_presult::~inode_management_service_remove_presult() noexcept {
}


inode_management_service_hdag_put_args::~inode_management_service_hdag_put_args() noexcept {
}


inode_management_service_hdag_put_pargs::~inode_management_service_hdag_put_pargs() noexcept {
}


inode_management_service_hdag_put_result::~inode_management_service_hdag_put_result() noexcept {
}


inode_management_service_hdag_put_presult::~inode_management_service_hdag_put_presult() noexcept {
}


inode_management_service_hdag_get_args::~inode_management_service_hdag_get_args() noexcept {
}


inode_management_service_hdag_get_pargs::~inode_management_service_hdag_get_pargs() noexcept {
}


inode_management_service_hdag_get_result::~inode_management_service_hdag_get_result() noexcept {
}


inode_management_service_hdag_get_presult::~inode_management_service_hdag_get_presult() noexcept {
}

}} // namespace

