/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#ifndef workflow_management_service_TYPES_TCC
#define workflow_management_service_TYPES_TCC

#include "workflow_management_service_types.h"

namespace hive { namespace workflow {

}} // namespace

#endif
