/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "workflow_management_service.h"
#include "workflow_management_service.tcc"

namespace hive { namespace workflow {


workflow_management_service_workflow_register_args::~workflow_management_service_workflow_register_args() noexcept {
}


workflow_management_service_workflow_register_pargs::~workflow_management_service_workflow_register_pargs() noexcept {
}


workflow_management_service_workflow_register_result::~workflow_management_service_workflow_register_result() noexcept {
}


workflow_management_service_workflow_register_presult::~workflow_management_service_workflow_register_presult() noexcept {
}


workflow_management_service_workflow_deregister_args::~workflow_management_service_workflow_deregister_args() noexcept {
}


workflow_management_service_workflow_deregister_pargs::~workflow_management_service_workflow_deregister_pargs() noexcept {
}


workflow_management_service_workflow_deregister_result::~workflow_management_service_workflow_deregister_result() noexcept {
}


workflow_management_service_workflow_deregister_presult::~workflow_management_service_workflow_deregister_presult() noexcept {
}

}} // namespace

