/**
 * Autogenerated by Thrift Compiler (0.18.1)
 *
 * DO NOT EDIT UNLESS YOU ARE SURE THAT YOU KNOW WHAT YOU ARE DOING
 *  @generated
 */
#include "storage_management_service.h"
#include "storage_management_service.tcc"

namespace hive { namespace storage {


storage_management_service_put_args::~storage_management_service_put_args() noexcept {
}


storage_management_service_put_pargs::~storage_management_service_put_pargs() noexcept {
}


storage_management_service_put_result::~storage_management_service_put_result() noexcept {
}


storage_management_service_put_presult::~storage_management_service_put_presult() noexcept {
}


storage_management_service_get_args::~storage_management_service_get_args() noexcept {
}


storage_management_service_get_pargs::~storage_management_service_get_pargs() noexcept {
}


storage_management_service_get_result::~storage_management_service_get_result() noexcept {
}


storage_management_service_get_presult::~storage_management_service_get_presult() noexcept {
}


storage_management_service_async_put_args::~storage_management_service_async_put_args() noexcept {
}


storage_management_service_async_put_pargs::~storage_management_service_async_put_pargs() noexcept {
}


storage_management_service_async_put_result::~storage_management_service_async_put_result() noexcept {
}


storage_management_service_async_put_presult::~storage_management_service_async_put_presult() noexcept {
}


storage_management_service_async_get_args::~storage_management_service_async_get_args() noexcept {
}


storage_management_service_async_get_pargs::~storage_management_service_async_get_pargs() noexcept {
}


storage_management_service_async_get_result::~storage_management_service_async_get_result() noexcept {
}


storage_management_service_async_get_presult::~storage_management_service_async_get_presult() noexcept {
}

}} // namespace

